name: Deploy Miranda Dashboard

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: '18.18.0'
    - name: Install requeriments
      run: npm install
    - name: Build the project
      run: npm run build
      env:
        VITE_API_DEPLOY: ${{ secrets.VITE_API_DEPLOY }}
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-3'   
        SOURCE_DIR: 'dist'     